### PR TITLE
[PR] Creating basic image classifier with Elixir

### LINKED ISSUE #1: Epic: Image Classifier
Once we are uploading images dwyl/imgup#51 
We want to classify the images and suggest meta tags to describe the images so that they become "searchable".
That means pulling any text out of images using OCR.
And attempting to find any detail in images that can be useful.

We aren't going build our own models from scratch. but we are going to ...

# Todo

+ [x] Research the available models, services/APIs we can use to send an image that classify images
+ [x] Research available OCR services or models.
  + [x] If there is an _Open Source_ OCR model we can run on our own infra e.g. €20/month on Fly.io share!!
+ [x] Images that are uploaded from a Camera or Smart Phone contain `metadata` including `camera type`/`model`, `location` (where the photo was taken), `ISO`, `Shutter`, `Focal Length`, `Original Resolution`, etc. We want to capture this and feed it into the classifier. #3 
+ [x] The objective of the classifier is to _attempt_ to _describe_ the image and return a few keywords. 

+ [x] If it makes more sense to have this as a standalone `app` (_separate from `imgup`_) then feel free to create a `new` repo! Then just send the data to the standalone app and receive `JSON` data in response. 💭 

@LuchoTurtle please leave comments with your research. 🙏 

# Context

We want to be able to upload images in our `App` and have them become an `item` of content. 
i.e. I take a photo of a messy kitchen and it becomes "Tidy The Kitchen" with a small thumbnail of the image.
If I tap on the thumbnail I see the full-screen. But the _Text_ is the important part.

The reason we want to have a "**_Visual_ Todo List**" is that it becomes easy for people who don't yet read (think toddlers) or people who don't read well (people who only have basic literacy) to follow instructions.

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #1 

This creates a simple image classifier with [`Bumblebee`](https://github.com/elixir-nx/bumblebee) and performs **image captioning** tasks that return a descriptive text of the image (not to be confused with **image classification**, which yields a weighted list of predictions).

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
I'm having immense trouble previewing the image and copying it to the DOM before consuming it. 
In order to actually use the image to classify it, I need to [`consume it`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#consume_uploaded_entries/3). However, this effectively removes the image entry from the temporary folder and I lose access to it to show to the person.

I've tried using the [`image_live_preview`](https://elixirforum.com/t/how-does-liveview-image-blob-preview-works/54818) function but it only works **if the entry is not consumed**, which is not possible in our scenario.

I'm trying to circumvent this by using an additional `<input>`, copying the file contents and displaying it in the DOM. But this, for some odd reason, makes it so that `handle_progress/3` is not called, which in turn doesn't consume the entry.

```elixir
allow_upload(:image_list,
       accept: ~w(image/*),
       auto_upload: true,
       progress: &handle_progress/3,
       max_entries: 1,
       chunk_size: 4_000,
       max_file_size: 64_000
     )}
```

I've tried many ways of doing this but I can't seem to figure it out. I could copy the file path to an `upload` directory, but that would mean that I'd need to manage **all of the uploaded images, their correct deletion (even if the person crashes the `LiveView`)**, which is something I really don't want to "waste" time on.

**Comment by nelsonic** [comment]
@LuchoTurtle maybe a quick sketch (_paper_ notebook flow diagram) of what you're trying to do will help _others_ on the team understand where you're stuck. 💭

**Comment by LuchoTurtle** [comment]
I've added virtually all of the documentation and the application is now functional.
I'm just having some trouble with having the tests covering 100% of the application. Because I'm using `Task.async`, I could technically add a `sleep` method for it to wait for the model to predict a given image. However, I feel like that's a "hack"/dirty copout.

I've been researching on how to get this to work, namely form:
- https://elixirforum.com/t/cant-use-task-async-within-liveview/32940/2
- https://medium.com/elixir-learnings/testing-a-phoenix-liveview-that-does-an-async-operation-after-mount-b8ec27e6c167

But haven't had good results on this.

I'm trying to implement a supervisor to do this (from https://elixirforum.com/t/best-way-of-doing-an-integration-test-that-spans-a-task-start/39429/2) but I'm struggling to get it to work.

Other than that, the app *works* (although it does not show the image after submitting, which is something I wanted to get to work as well, but it's not "essential")

**Comment by LuchoTurtle** [comment]
This should be mergeable 👌

**Comment by nelsonic** [comment]
@LuchoTurtle demo on Standup this morning was superb! 😍 
PR is still assigned to you. Happy to review it later today. 👌 
Meanwhile there are a couple of tasks you can crack on with: #3 & #4 😉

**Comment by LuchoTurtle** [comment]
I've reassigned it to myself because I want to make some additional changes. I'll hand it over to you after those.

**Comment by nelsonic** [comment]
cool-cool-cool

**Comment by LuchoTurtle** [comment]
Reassigning back to you 👌

**Comment by nelsonic** [comment]
Gonna pick this up (run + review) as soon as I get a decent chunk of alone time.... 🤞 ⏳

**Review by nelsonic — APPROVED** [review]
Excellent work @LuchoTurtle! 🥇 
Merging so other people can learn along. 👌

**Pull request merged**
