### PR TITLE
separate folder for hnswlib

### PR DESCRIPTION
**Pull request by ndrean**
To further clean the main Readme, I propose to create a separate folder "hnswlib" and reference it in the main README.

It contains:
- README
- hnswlib.exs file

### CODE REVIEW

**Review by LuchoTurtle — CHANGES_REQUESTED** [review]
Looks good, thank you :) 

Can I ask you to revert the formatting changes from the `README` file? I assume you're running a format command that is changing the code from the `README` that is unrelated to this PR.

After that, I'll merge it ASAP :)

**Comment by ndrean** [comment]
Did I??? The second time? I hardly touched the main README, did not use `mix format` if this is what you mean, only saved after removing a paragraph.

**Comment by LuchoTurtle** [comment]
@ndrean I have a feeling you're using VSCode and it's saving automatically. When saved automatically, it perhaps formats the README. :P 

Before committing your code, maybe check when the changes are being made. That way you know if your IDE is pulling your leg haha. 

But yeah, if you could just revert those partial changes in the README, I'll merge this straight away!

**Comment by LuchoTurtle** [comment]
Looks good, thanks!

**Pull request merged**
