### PR TITLE
#18 2) Embedding & knn

### PR DESCRIPTION
**Pull request by ndrean**
I added the semantic search. Still no tests since this is considered as the first draft.

To note: I search for **the** closest neighbour. This means that you should always receive an answer (unless the Index is empty). It might not be relevant though, in the sense that it is the closest, but might not be close! For this, you may need a cut-off distance.

But before going too far in this, I let you read the code and Readme as I am sure there are plenty of things to improve (because I had to adapt my code). I will keep updating when I find gray zones.

I can also add some process flow images to help (?) the understanding.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Thanks for the PR.
I'll take a look at https://github.com/dwyl/image-classifier/pull/43#issue-comment-box first and then after we get that merged, we can expand on this one :D

**Comment by ndrean** [comment]
I continued with this part. You will probably need some time. I am still 100% happy with this work because I don't really see how to find a clear "cut-off" distance to ignore responses that are not meaningful. This needs to be discussed.

**Comment by LuchoTurtle** [comment]
Thanks for continuing the work @ndrean , it is so, so, so much appreciated, you have no idea ❤️ .
I've reviewed https://github.com/dwyl/image-classifier/pull/43 and it looks great. I've made some changes to the README, which will maybe create conflicts with this PR.

Because https://github.com/dwyl/image-classifier/pull/43 is a "prequel" to this one, maybe it's best to just pause development in this PR until https://github.com/dwyl/image-classifier/pull/43 is merged. This is only to simplify your work ahead and not having to deal with conflicts. However, you can finish it if you want, it's fine either way.

> I am still not totally happy with this work because I don't really see how to find a clear "cut-off" distance to ignore responses that are not meaningful. This needs to be discussed.

I haven't tried the code in this PR yet. I will once #43 is merged (since it's foundational).

> The drawing I made https://github.com/dwyl/image-classifier/issues/18#issuecomment-1852864266 might help to grasp what is going on here.

Thanks for the referral :). I think the README you've created is already explicit and I fully understand what is going on/what the process is :D .

Nonetheless, thanks again for these PRs, I'm learning A LOT! 

I'll try getting testing in #43 working ASAP in order to get it merged so this PR can be finished without a hitch :)

**Comment by ndrean** [comment]
@LuchoTurtle I bumped into  [this blog on Fly.io on Semantic search through the Hex docs](https://fly.io/phoenix-files/real-world-machine-learning-on-fly-gpu/). I though about this but this task intimidated me. It might be very helpful.

**Comment by LuchoTurtle** [comment]
Thanks for sharing the article, it was really interesting! THe process is actually quite similar to the one you've implemented here! (albeit using a different model).

It's a great resource to quote on the README once this PR is merged and to compare between different models.

It's a shame that GPUs are mighty expensive on `fly.io` currently :/

**Comment by ndrean** [comment]
Added another PR after #18 commited.

**Pull request closed without merging**
