### PR TITLE
resample audio to 16kHz: #80

### PR DESCRIPTION
**Pull request by ndrean**
Small JS optimisation that resamples the audio from (usually) 48kHz to 16kHz.

JS code only. You can test it.

Next (2/2 for #80) is Readme.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Looks good and it seems to be working @ndrean . 

Instead of opening a new PR, can you add the changes to the README on this one? Just to keep the feature contained to this PR and making it easier for people to go over it in the future = D

**Review by LuchoTurtle — CHANGES_REQUESTED** [review]
Looks good and it seems to be working @ndrean  . 

Instead of opening a new PR, can you add the changes to the README on this one? Just to keep the feature contained to this PR and making it easier for people to go over it in the future = D

**Comment by ndrean** [comment]
@LuchoTurtle 
Check readme.

**Review by LuchoTurtle — APPROVED** [review]
Thank you for the changes :) 

Just small feedback:

- please refrain from formatting the whole README in these PRs. It makes it difficult to review the changes related to the feature the PR is addressing :P 
- I can't really make changes to the PR because you are merging from your `main` instead of creating a `branch`. So I can't push commits upstream to your fork. 

Regardless, awesome PR as always and I really thank you for effort you put in, it's greatly appreciated as always! :D

**Comment by ndrean** [comment]
ah, sorry, yes, how stupid, I was on main, I did not pay attention.

**Pull request merged**
