### PR TITLE
[PR] Added `gen_magic` check by `magic numbers` for image input validation

### LINKED ISSUE #36: Error deploying due to `toastify-js`
More context in https://github.com/dwyl/image-classifier/actions/runs/7260046156/job/19778403428.

The deploy script is not working because of `toastify-js`.

### PR DESCRIPTION
**Pull request by ndrean**
closes #36 #35

No tests yet. 
Comments added in the Readme.
I used pnpm to get the toasts working (needed to check GenMagic), and modified Dockerfile.
Have a look.

### CODE REVIEW

**Comment by ndrean** [comment]
One remark on `handle_progress`.

The doc shows something like this:

```elixir
defp handle_progress(:image_list, entry, socket) do
    #if entry.done? do
      uploaded_file =
        consume_uploaded_entry(socket, entry, fn %{} = _meta ->
          {:ok, entry}
        end)
    end

    {:noreply, socket}
  end
```

I prefer to remove one level like below with a guard instead. This handle_progress can become more complicated and this cleans the code abit, and credo will give you warnings about depth level. 
You still need the "headless" version because handl_progress sends chunks, so you need some termination (even if void as this is the case here).

```elixir
defp handle_progress(:image_list, entry, socket) when entry.done? do
      uploaded_file =
        consume_uploaded_entry(socket, entry, fn %{} = _meta ->
          {:ok, entry}
        end)
    end
    {:noreply, socket}
  end

defp handle_progress(_, _, socket), do: {:noreply, socket}
```

If you agree, I can modify the Readme accordingly.

**Comment by ndrean** [comment]
100% tests.

**Comment by LuchoTurtle** [comment]
Thanks for the PR @ndrean .

Once it's finished, you can assign it to me. 
If you want to write a small section on the changes you've made in the PR, you can do so. Otherwise, I'll pick it up and document the changes so the `README` is fully completed with all of the changes that was made to it :)

**Comment by ndrean** [comment]
@luchoturtle
I did not want to bring high focus on this little change so I essentially only changed "## 9.5 Adding double MIME type check and Showing feedback to the person in case of failure" in the Readme. 

In the code, I added on function and used it in the `handle_progress`.

Notice that I changed the `handle_progress` into a multi-clause function: one with a guard `when entry.done?`, one default callback for the chunks. This cleans the code a bit.

**Review by nelsonic — APPROVED** [review]
Thanks @dependabot 🤖 👌

**Comment by LuchoTurtle** [comment]
Trying to run this with `mix phx.server` and stumbling upon

```
cc -std=c99 -g -Wall -Wextra -Werror  src/apprentice.c  -lm `pkg-config --cflags --libs libmagic 2>/dev/null || echo "-lmagic"` -o priv/apprentice
src/apprentice.c:37:10: fatal error: 'magic.h' file not found
#include <magic.h>
         ^~~~~~~~~
1 error generated.
make: *** [priv/apprentice] Error 1
could not compile dependency :gen_magic, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile gen_magic --force", update it with "mix deps.update gen_magic" or clean it with "mix deps.clean gen_magic"
```

Definitely `libmagic`-related. But given that I've it installed with `homebrew`, this one is weird 🤔

**Review by LuchoTurtle — APPROVED** [review]
Thank you for the PR @ndrean :)

I've made some changes that fixed some typos and added more information on installing `libmagic` so it works for everyone.

**Pull request merged**
