### PR TITLE
[PR] Speed up the boot time and scaling with `fly.io`

### LINKED ISSUE #6: Feat: Use the best available model
As noted in https://github.com/dwyl/image-classifier/pull/5#issuecomment-1806767583 the mini model currently deployed returns _basic_ classification. 💭 
We want to use the best available pre-trained model to maximise the effectiveness of classification. ✨ 

The Fly.io instance is currently: https://fly.io/dashboard/dwyl-img-class `shared-cpu-1x@256MB`
imgai-machine-256

When the VM is not in-use it gets paused: https://fly.io/blog/fly-now-with-power-pause/

imgai-paused

So we can easily bump this to `2 GB` or `4 GB` RAM without fear of it costing us a fortune.
https://fly.io/docs/about/pricing/#compute

fly-perf-core

Please:

+ [ ] Update the code to use the best (biggest?) available model
+ [x] Increase the Fly.io instance `RAM` size and `CPU` to _comfortably_ match the requirement of the best model.
  > If the model is `3GB` use a `4GB` instance. If the model is `15GB` use `16GB` instance.
+ [x] Document which model you're using and why and the steps (`fly` CLI commands) you used to scale up.

Thanks. 

> **Note**: **Boss Level**: if there's a _significant_ advantage to using an ` A100 GPU` please play with it:
https://fly.io/docs/about/pricing/#gpus-and-fly-machines
image

> Just don't leave it running over a weekend ... 💰 🔥 😉 
> and document _everything_ you learn along the way. 👌 
> Knowing your way around `A100` will be a good talking point when you interview at `Anthropic`. 😜 

# Chore

+ [x] Fix auto-deployment ...

image

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #6 

This attempts to fix the deployment issue, decrease boot time and documents scaling the solution up with `fly.io`.

The machine we're using is `performance-4x`. This was the minimum preset I tried that worked. Other presets with weaker resources would run out of memory.

image

It is using `https://huggingface.co/Salesforce/blip-image-captioning-base`. We can upgrade to `large` at a later stage, but I didn't get it to work locally. 
From https://github.com/elixir-nx/bumblebee/issues/269, perhaps @ndrean could share how he did it?

### CODE REVIEW

**Comment by nelsonic** [comment]
Looking good. 👌

**Comment by LuchoTurtle** [comment]
This should be mergeabe 🆗

**Comment by ndrean** [comment]
@LuchoTurtle I am probably going to disappoint you or comfort you, depends. Locally, "large" works like "base" but this doesn't work with Docker. No explanation, and I tried ....

**Comment by ndrean** [comment]
@LuchoTurtle 

The joy of open source. Maybe try to change your dependencies to:

```elixir
{:bumblebee, git: "https://github.com/elixir-nx/bumblebee", branch: "main", override: true},
{:nx, git: "https://github.com/elixir-nx/nx.git", sparse: "nx", override: true},
```

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle looks good. 🤞

**Pull request merged**
